if(EXISTS "/Users/bengamble/FasterAPI/gtest_http1_parser[1]_tests.cmake")
  include("/Users/bengamble/FasterAPI/gtest_http1_parser[1]_tests.cmake")
else()
  add_test(gtest_http1_parser_NOT_BUILT gtest_http1_parser_NOT_BUILT)
endif()
