if(EXISTS "/Users/bengamble/FasterAPI/gtest_webtransport[1]_tests.cmake")
  include("/Users/bengamble/FasterAPI/gtest_webtransport[1]_tests.cmake")
else()
  add_test(gtest_webtransport_NOT_BUILT gtest_webtransport_NOT_BUILT)
endif()
