if(EXISTS "/Users/bengamble/FasterAPI/gtest_tcp_socket[1]_tests.cmake")
  include("/Users/bengamble/FasterAPI/gtest_tcp_socket[1]_tests.cmake")
else()
  add_test(gtest_tcp_socket_NOT_BUILT gtest_tcp_socket_NOT_BUILT)
endif()
